### ISSUE TITLE
Does not work with Alfred 3.0

### ISSUE THREAD

**Issue by sashagolds** [charliecm/alfred-hyperlink#2]
This doesn’t work with Alfred 3 (typing copylink and hitting enter does not bring up a list of tabs)

**Comment by charliecm** [comment]
@sashagolds Which browser are you using?

**Comment by sashagolds** [comment]
Thanks for the quick response! Safari 9.1.1

**Comment by sashagolds** [comment]
@charliecm — right after I replied I restarted Safari and tried again and it worked perfectly. My issue must have been some sort of strangeness related to a new Alfred 3 install.

Cheers!
