### ISSUE TITLE
Not copying

### ISSUE THREAD

**Issue by jercle** [charliecm/alfred-hyperlink#3]
Hi, this doesn't seem to copy and create the hyperlink for me.

I can Cmd + C to copy it, but pressing Enter does nothing.

**Comment by charliecm** [comment]
Does a notification appear when you press enter? If so, where did you try pasting the hyperlink?

**Comment by jercle** [comment]
Hey, no notification appears and nothing goes to the clipboard.

**Comment by jercle** [comment]
This is now working correctly.....so...this can be closed.
Not sure what resolved it. Only thing I did related to Alfred was disable one Workflow (Spotify Mini Player), however the issue didn't return when I re enabled it.

**Comment by jercle** [comment]
I did, however, also upgrade to Alfred 3.0.2
